### ISSUE TITLE
doesn't appear to be working in 3.6.3

### ISSUE THREAD

**Issue by skeetermedia** [bobopinna/moodle-enrol_autoenrol#13]
I am having issues with it working in 3.6.3
I installed the plugin and configured it into a course I want all users to be enrolled in. I log in as a typical user and it goes to the course but doesn't enrol the user.
what am I doing wrong?
(I had this working fine in a 2.3 version way back when but I have recently upgraded to 3.6.3)
Rob

**Comment by slydrone** [comment]
cant get it to work in 3.7 are there any detailed instructions?

**Comment by bobopinna** [comment]
I checked, It works in 3.7.
First you find how enable the plugin: https://docs.moodle.org/en/Enrolment_plugins in your moodle site.
Then you need to add an Auto Enrol instance to a course: https://docs.moodle.org/37/en/Enrolment_methods#Managing_enrolment_methods
You can manage Auto Enrol settings clicking on the gear icon. If you want to see all settings just click the Show more... link.
Remember to save changes before leave the page.

Note: when you set to enrol users on site login the users will be enrolled at first login but they see the new course in their dashboard from the next login. This can be fixed because moodle loads the users courses and then calls the enrol hook.

**Comment by slydrone** [comment]
We’ve sorted it now thanks. 

Regards
Gordon Mills


> On 14 Oct 2019, at 14:16, Roberto Pinna <notifications@github.com> wrote:
> 

﻿
I checked, It works in 3.7.
First you find how enable the plugin: https://docs.moodle.org/en/Enrolment_plugins in your moodle site.
Then you need to add an Auto Enrol instance to a course: https://docs.moodle.org/37/en/Enrolment_methods#Managing_enrolment_methods
You can manage Auto Enrol settings clicking on the gear icon. If you want to see all settings just click the Show more... link.
Remember to save changes before leave the page.

Note: when you set to enrol users on site login the users will be enrolled at first login but they see the new course in their dashboard from the next login. This can be fixed because moodle loads the users courses and then calls the enrol hook.
