### ISSUE TITLE
Little Help

### ISSUE THREAD

**Issue by nimchak** [bobopinna/moodle-enrol_autoenrol#27]
Moodle Noob Here,
I have installed the plugin.  But it's still not clear to me how this is supposed to work.

I need all my users to be enrolled into an existing course.  After setting the settings and enabling the plugin my test account is not enrolled into the test.  

How would I set the setting to cause all users to be automatically enrolled?
What other actions do i have to take?
Are there scheduled tasks that have to run first?

Thanks
Nima

**Comment by bobopinna** [comment]
Hello Nima,
autoenrol works on user interaction, you can set if users are enrolled on site login or course access in instance settings.
If you need to enrol users in bulk mode, you need to enable the Synchronise Autoenrol task under Site Admininstration -> Server -> Tasks -> Scheduled Task to do that. Pay attention because if you use autoenrol on a large number of courses this task could reduce your site performance.
If you need to synchronise just few courses enrolment you can use the CLI script /moodle/enrol/autoenrol/cli/sync_course_autoenrol.php passing to it the courseid, this could be used only if you can access to the CLI on your server.

HTH,
Roberto
