### ISSUE TITLE
New enrolment option

### ISSUE THREAD

**Issue by Brada65** [bobopinna/moodle-enrol_autoenrol#37]
Great plugin Roberto! Happy Holidays!
First, I will start with my environment / requirements: I am working in non-profit agency for helping new immigrants to settle in Canada, and we are using modle for online courses in our everyday work, and our requirements is that client login to the moodle - enter the enrolment key in a block on the landing page (dashboard), and in one click on the button "Enrol me" is enroled in the course, and can see the course main page.
We can't use self-enrolment (core plugin) because in order to use enrolment key client need to know to browse through the platform or follow the link, and in our case that is not possible from various reasons. We are using now Easy enrolment from Dearborn school board, but I needed to modify that plugin to work for us (to use our enrolment keys from mdl_groups table), and it doesn't have options like your plugin and that would be great for us as "unenrol inactive users" after ... days.
Is it possible maybe to add to your plugin option at "Enrol When" where already 3 options are existing - one more "Enrolment key is used" of course that will require additional block plugin that can be added to the landing page. When somebody choose that option, additional field will open for enrolment key for the course itself (same as in self-enrolment), that way it will be possible to enrol clients in courses without groups, and maybe one more field (yes, no) to choose if group enrolment keys are used (same that self-enrolment is using, to search for the keys in mdl_groups table).
This way we (and anybody else) will have lot of enrolment options in just one plugin: on login, on loading the course, and on use of the enrolment key (for course or groups within the course).
Thank you for all your work on the moodle plugins!

**Comment by bobopinna** [comment]
Hello,
The two plugins differs to much to integrate them:
- Autoenrol creates new groups and enrols/adds to groups users using user profile fields.
- Easy enrol uses existing groups and enrols/adds to groups users using codes.

Autoenrol can't provide codes for groups that do not exists.
I think you can not also use self-enrolment because enrolment keys and group keys could be the same in different courses/groups opposite to Easy enrol that generate unique codes site wide.

I checked your request but I think it would be better to add missing features to Easy Enrol; unenrol inactive users is a standard feature for many enrolment plugins. Try to ask for it to Easy enrol developers.

HTH,
Roberto
