### ISSUE TITLE
When guest user access is enabled autoenrol does not work with setting enrol on "Loading the course"

### ISSUE THREAD

**Issue by dasistwas** [bobopinna/moodle-enrol_autoenrol#42]
When guest user access is enabled the auto enrol does not work. The reason: enrol/index.php page is not accessed and therefore the hook, the plugin is using is not called.

### Workaround

You can embed an iframe on the course page with that link: https://moodleroot/enrol/index.php?id=XXXX and hide the iframe. Where XXXX is the course id andd "moodleroot" the URL to your Moodle site.

### Possible solution

Instead of using the enrol/index.php page to trigger the enrolment, an observer could be used that is called when the course page is viewed.

**Comment by bobopinna** [comment]
The guest access hook is called by the require_login function before enrol check.
In the past autoenrol workaroud this problem using the try_autoenrol method that is called before try_guestaccess.
Unfortunately using this method Moodle App users were autoenrolled when they do a search or browse categories that show course with autoenrol.
So I preferred to not use it anymore.
I think that a Moodle core patch is needed to solve this problem with guest access enabled courses.
All enrol methods are affected from it.

I've tried to add an observer for course page view.
It enrol users but the page needs to be reloaded in order to view the enrolment.
I don't think that this could be the solution: the observer could overload sites with a lot of users.
