### ISSUE TITLE
Write Access Failed during Install

### ISSUE THREAD

**Issue by shivanraptor** [bobopinna/moodle-enrol_autoenrol#43]
I'm trying to install the plugin in Moodle 4.0.4 via uploading ZIP file

```
Validating enrol_autoenrol ... Error
  [Error] Write access check [/var/www/html/enrol] 
Installation aborted due to validation failure
```
But the folder mentioned is already there, having 775 as folder permission, with the user group `myadminacc:apache`

OS: RHEL8
Apache

**Comment by shivanraptor** [comment]
After setting `setenforce Permissive` and setting the folder to `777`, the folder can be written, however, the following error will be shown:

```
There is a request to install plugin AutoEnrol (enrol_autoenrol) version 2022062000 from the Moodle plugins directory on this site. However, the plugin installation pre-check failed (reason code: remoteunavailable).
```

**Comment by bobopinna** [comment]
I'm sorry but the plugin installation from Moodle plugin directory is not managed from plugins as AutoEnrol. 
It's done from Moodle core.

I think you need to check and set the right SELinux context on your Moodle directory in order to work without using Permissive mode. You also need to check connection rules from your server to Moodle server to solve the second problem.

The easy way to install and keep secure your server is to manually install your plugins on your server.
You can find all documentation here: https://docs.moodle.org/400/en/Installing_plugins#Installing_manually_at_the_server.

HTH,
Roberto
