### ISSUE TITLE
Issue: User Filter with profile field 

### ISSUE THREAD

**Issue by erudisiya** [bobopinna/moodle-enrol_autoenrol#46]
I am facing an issue with the auto-enroll Moodle plugin when enrolment has user filters. Without user filters it works well. 
Does anyone face the same issue? I am facing the issue with any type of user profile field like text, or dynamic dropdown. Please help.
in lib.php return $info->is_available($information, false, $user->id); in method name check_rule() is not working properly.

**Comment by bobopinna** [comment]
We use User Filter with several user profile fields rules without any problem.
Please could you give me more information? Which Moodle and which Autoenrol plugin version do you use?
If you found a bug, feel free to share it with us.

**Comment by erudisiya** [comment]
Hi, Thanks for your reply.

- Auto-enrolment plugin details what I am using

$plugin->version = 2022062000;
$plugin->release = '2.3.9';  

- I am using [Moodle](http://moodle.org/) [4.0.1+ (Build: 20220512)](http://docs.moodle.org/dev/Releases)

- Dynamic menu profile field = 2017021201

- Cron runs in background with 1 min interval

User with custom profile field value 
<img width="405" alt="Screenshot 2023-05-09 at 6 45 00 PM" src="https://github.com/bobopinna/moodle-enrol_autoenrol/assets/124784950/bc49c88f-0ea8-47ff-9c02-4ba9e8644477">
Dynamic profile field setup 
<img width="808" alt="Screenshot 2023-05-09 at 6 50 00 PM" src="https://github.com/bobopinna/moodle-enrol_autoenrol/assets/124784950/21a96a4f-b1dc-4528-94cb-cf3b59a75b2c">
<img width="1145" alt="Screenshot 2023-05-09 at 6 51 05 PM" src="https://github.com/bobopinna/moodle-enrol_autoenrol/assets/124784950/a329ad0d-22ab-4352-9723-76cbc3f2db43">
<img width="1286" alt="Screenshot 2023-05-09 at 6 51 52 PM" src="https://github.com/bobopinna/moodle-enrol_autoenrol/assets/124784950/5103140d-a979-4005-b972-1623789d033d">
Here are all details of what I am facing right now. Please help.

**Comment by bobopinna** [comment]
Hello,
Autoenrol (2022062000) was tested on Moodle 4 and should works with standard and core custom field.
It uses Moodle availability checker in order to test User filter but I never tested Dynamic Dropdown custom field plugin so the problem could be there or in availability checker.
Did you tested a Dynamic Dropdown custom field in activities or resources availability condition?
If it also doesn't works with activities and resources the problem should be outside the autoenrol plugin but a more deep evalution is needed to be sure.
